version: "3.1"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    networks:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: johnson@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 0

networks:
  backend:
