version: "3.1"

services:
  web:
    build: .
    ports:
      - "443:4000"
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    networks:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  backend:
