version: "3.6"

services:
  web:
    build: .
    ports:
      - "443:4000"
    restart: on-failure
    environment:
      DEBUG: "false"
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    networks:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
  db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  backend:
